### ISSUE TITLE
运行train_whiten(nli).py出现内存错误

### ISSUE THREAD

**Issue by Anery** [autoliuweijie/BERT-whitening-pytorch#2]
你好，我想用roberta训练均值，但出现了内存错误：

Traceback (most recent call last):
  File "train_whiten(nli).py", line 79, in <module>
    main()
  File "train_whiten(nli).py", line 63, in main
    a_vecs_train = sents_to_vecs(a_sents_train, tokenizer, model, POOLING, MAX_LENGTH)
  File "/data/yuany/BERT-whitening-pytorch/all_utils.py", line 65, in sents_to_vecs
    vecs = np.array(vecs)
numpy.core._exceptions.MemoryError: Unable to allocate 2.81 GiB for an array with shape (981382, 768) and data type float32

请问你碰到过这个问题吗？

**Comment by autoliuweijie** [comment]
应该是你用的来计算均值的语料太大了，而内存却不足够。
你可以减小语料试一试，我们实验表明用于计算均值的语料不必太大。
